// Mock data for development without Supabase
export const mockProperties = [
  {
    id: '1',
    title: 'Burj Khalifa Penthouse - Sky Collection',
    slug: 'burj-khalifa-penthouse-sky-collection',
    property_type: 'penthouse' as const,
    price_aed: 45000000,
    price_usd: 12250000,
    bedrooms: 5,
    bathrooms: 6,
    size_sqft: 12000,
    size_sqm: 1115,
    location: 'Downtown Dubai',
    neighborhood: 'Burj Khalifa District',
    description: 'Exclusive 5-bedroom penthouse on the 118th floor of the world\'s tallest building. Unparalleled 360° views of Dubai\'s skyline, private elevator, Armani Casa interiors, and access to the Armani Hotel spa and fine dining.',
    features: ['Private Elevator', 'Armani Casa Interiors', '360° Skyline Views', 'Smart Home Automation', 'Concierge Service', 'Spa Access', 'Wine Cellar', 'Private Cinema'],
    status: 'available' as const,
    completion_date: null,
    developer: 'Emaar Properties',
    payment_plan: null,
    rental_yield: 5.2,
    roi_estimate: 6.5,
    golden_visa_eligible: true,
    main_image_url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1600',
    gallery_images: [
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800',
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
      'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800'
    ],
    video_tour_url: null,
    is_featured: true,
    views_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Palm Jumeirah Signature Villa',
    slug: 'palm-jumeirah-signature-villa',
    property_type: 'villa' as const,
    price_aed: 85000000,
    price_usd: 23140000,
    bedrooms: 7,
    bathrooms: 8,
    size_sqft: 15000,
    size_sqm: 1394,
    location: 'Palm Jumeirah',
    neighborhood: 'Frond G',
    description: 'Ultra-luxury 7-bedroom beachfront villa with 100 feet of private beach, infinity pool overlooking the Arabian Gulf, private cinema, gym, and spa. Contemporary design by world-renowned architects.',
    features: ['100ft Private Beach', 'Infinity Pool', 'Private Cinema', 'Home Gym', 'Spa', 'Smart Home', 'Staff Quarters', 'Panoramic Gulf Views'],
    status: 'available' as const,
    completion_date: null,
    developer: 'Nakheel',
    payment_plan: null,
    rental_yield: 4.8,
    roi_estimate: 7.2,
    golden_visa_eligible: true,
    main_image_url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600',
    gallery_images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=800',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'
    ],
    video_tour_url: null,
    is_featured: true,
    views_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Marina Bay Penthouse - Waterfront Living',
    slug: 'marina-bay-penthouse-waterfront-living',
    property_type: 'penthouse' as const,
    price_aed: 28000000,
    price_usd: 7620000,
    bedrooms: 4,
    bathrooms: 5,
    size_sqft: 8500,
    size_sqm: 790,
    location: 'Dubai Marina',
    neighborhood: 'Marina Promenade',
    description: 'Stunning 4-bedroom penthouse with floor-to-ceiling windows, wraparound terrace, infinity pool, and direct marina views. Walking distance to world-class dining, shopping, and nightlife.',
    features: ['Private Pool', 'Wraparound Terrace', 'Marina Views', 'Smart Home', 'Walk-in Closets', 'High-End Appliances', 'Maid\'s Room', 'Private Parking'],
    status: 'available' as const,
    completion_date: null,
    developer: 'Emaar Properties',
    payment_plan: null,
    rental_yield: 6.5,
    roi_estimate: 8.0,
    golden_visa_eligible: true,
    main_image_url: 'https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=1600',
    gallery_images: [
      'https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=800',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800'
    ],
    video_tour_url: null,
    is_featured: true,
    views_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Jumeirah Bay Island - Bulgari Villa',
    slug: 'jumeirah-bay-island-bulgari-villa',
    property_type: 'villa' as const,
    price_aed: 55000000,
    price_usd: 14970000,
    bedrooms: 6,
    bathrooms: 7,
    size_sqft: 12500,
    size_sqm: 1161,
    location: 'Jumeirah Bay Island',
    neighborhood: 'Bulgari Resort',
    description: 'Exclusive 6-bedroom villa within the Bulgari Resort community. Private yacht berth, beach access, Bulgari-designed interiors, and access to the resort\'s Michelin-starred restaurants and luxury amenities.',
    features: ['Private Yacht Berth', 'Beach Access', 'Bulgari Interiors', 'Resort Amenities', 'Infinity Pool', 'Landscaped Gardens', 'Smart Home', 'Concierge'],
    status: 'available' as const,
    completion_date: null,
    developer: 'Meraas',
    payment_plan: null,
    rental_yield: 5.0,
    roi_estimate: 6.8,
    golden_visa_eligible: true,
    main_image_url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1600',
    gallery_images: [
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800',
      'https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=800'
    ],
    video_tour_url: null,
    is_featured: true,
    views_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Dubai Hills Estate - Golf Course Mansion',
    slug: 'dubai-hills-estate-golf-course-mansion',
    property_type: 'villa' as const,
    price_aed: 32000000,
    price_usd: 8710000,
    bedrooms: 6,
    bathrooms: 7,
    size_sqft: 11000,
    size_sqm: 1022,
    location: 'Dubai Hills Estate',
    neighborhood: 'Parkways',
    description: 'Luxurious 6-bedroom mansion overlooking the championship golf course. Expansive outdoor living areas, infinity pool, home cinema, gym, and direct golf course access. Perfect for families seeking tranquility.',
    features: ['Golf Course Views', 'Infinity Pool', 'Home Cinema', 'Gym', 'Landscaped Garden', 'Smart Home', 'Maid\'s Quarters', 'Private Garage'],
    status: 'available' as const,
    completion_date: null,
    developer: 'Emaar Properties',
    payment_plan: null,
    rental_yield: 5.8,
    roi_estimate: 7.5,
    golden_visa_eligible: true,
    main_image_url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1600',
    gallery_images: [
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800'
    ],
    video_tour_url: null,
    is_featured: false,
    views_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Dubai Creek Harbour - Waterfront Residences (Off-Plan)',
    slug: 'dubai-creek-harbour-waterfront-residences',
    property_type: 'off-plan' as const,
    price_aed: 6500000,
    price_usd: 1770000,
    bedrooms: 3,
    bathrooms: 4,
    size_sqft: 2800,
    size_sqm: 260,
    location: 'Dubai Creek Harbour',
    neighborhood: 'Creek Beach',
    description: 'Modern 3-bedroom apartment in Dubai\'s fastest-growing waterfront community. Stunning views of Dubai Creek Tower (under construction), private beach access, and 20/80 payment plan. Expected completion: Q4 2026.',
    features: ['Creek Tower Views', 'Beach Access', 'Smart Home', 'Balcony', 'Gym', 'Pool', 'Kids Play Area', 'Retail Podium'],
    status: 'off-plan' as const,
    completion_date: '2026-12-31',
    developer: 'Emaar Properties',
    payment_plan: '20/80 Post-Handover',
    rental_yield: 7.2,
    roi_estimate: 9.5,
    golden_visa_eligible: true,
    main_image_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1600',
    gallery_images: [
      'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
      'https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=800'
    ],
    video_tour_url: null,
    is_featured: false,
    views_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Business Bay - Canal View Apartment',
    slug: 'business-bay-canal-view-apartment',
    property_type: 'apartment' as const,
    price_aed: 3200000,
    price_usd: 871000,
    bedrooms: 2,
    bathrooms: 3,
    size_sqft: 1650,
    size_sqm: 153,
    location: 'Business Bay',
    neighborhood: 'Canal District',
    description: 'Prime investment opportunity: 2-bedroom apartment with Dubai Canal views. High rental demand, close to Downtown Dubai and DIFC. Perfect for investors seeking strong ROI and Golden Visa eligibility.',
    features: ['Canal Views', 'Balcony', 'Gym', 'Pool', 'Parking', 'Security', 'Retail Podium', 'Metro Access'],
    status: 'available' as const,
    completion_date: null,
    developer: 'Omniyat',
    payment_plan: null,
    rental_yield: 8.0,
    roi_estimate: 10.2,
    golden_visa_eligible: true,
    main_image_url: 'https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=1600',
    gallery_images: [
      'https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=800',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800'
    ],
    video_tour_url: null,
    is_featured: false,
    views_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Emirates Hills - Ultra-Luxury Mega Mansion',
    slug: 'emirates-hills-ultra-luxury-mega-mansion',
    property_type: 'villa' as const,
    price_aed: 120000000,
    price_usd: 32670000,
    bedrooms: 8,
    bathrooms: 10,
    size_sqft: 25000,
    size_sqm: 2323,
    location: 'Emirates Hills',
    neighborhood: 'Lake View',
    description: 'Dubai\'s most exclusive address: 8-bedroom mega mansion with private lake, championship tennis court, indoor and outdoor pools, 12-car garage, helipad, and staff accommodations for 10+. Epitome of ultra-luxury living.',
    features: ['Private Lake', 'Tennis Court', 'Helipad', 'Indoor Pool', 'Outdoor Pool', 'Wine Cellar', 'Private Cinema', 'Spa', '12-Car Garage', 'Staff Quarters'],
    status: 'available' as const,
    completion_date: null,
    developer: 'Private Developer',
    payment_plan: null,
    rental_yield: 4.0,
    roi_estimate: 5.5,
    golden_visa_eligible: true,
    main_image_url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600',
    gallery_images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=800',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'
    ],
    video_tour_url: null,
    is_featured: true,
    views_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
